apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elk-pvc
  namespace: elk
  annotations:
    volume.beta.kubernetes.io/selected-node: ""
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: csi-driver-lvm-linear
  resources:
    requests:
      storage: 10Gi